"""solicitacao_projeto_e_max_consultores

Revision ID: 00b38e9fa008
Revises: c58f1e7a3d90
Create Date: 2026-08-07 04:25:30.052767

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00b38e9fa008'
down_revision: Union[str, Sequence[str], None] = 'c58f1e7a3d90'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('solicitacao_projeto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('projeto_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('justificativa', sa.String(length=1000), nullable=False),
    sa.Column('status', sa.Enum('pendente', 'aprovada', 'recusada', name='status_solicitacao_projeto'), server_default='pendente', nullable=False),
    sa.Column('criado_em', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('respondido_por', sa.Integer(), nullable=True),
    sa.Column('respondido_em', sa.DateTime(), nullable=True),
    sa.Column('resposta', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['projeto_id'], ['projeto.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['respondido_por'], ['usuario.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_solicitacao_projeto_id'), 'solicitacao_projeto', ['id'], unique=False)
    op.create_index(op.f('ix_solicitacao_projeto_projeto_id'), 'solicitacao_projeto', ['projeto_id'], unique=False)
    op.create_index(op.f('ix_solicitacao_projeto_usuario_id'), 'solicitacao_projeto', ['usuario_id'], unique=False)
    op.add_column('projeto', sa.Column('max_consultores', sa.Integer(), server_default='3', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projeto', 'max_consultores')
    op.drop_index(op.f('ix_solicitacao_projeto_usuario_id'), table_name='solicitacao_projeto')
    op.drop_index(op.f('ix_solicitacao_projeto_projeto_id'), table_name='solicitacao_projeto')
    op.drop_index(op.f('ix_solicitacao_projeto_id'), table_name='solicitacao_projeto')
    op.drop_table('solicitacao_projeto')
    # ### end Alembic commands ###
