"""bloco1_avaliacao

Revision ID: 0351b6185bf1
Revises: ff536b09e0a2
Create Date: 2026-08-05 11:31:11.158087

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0351b6185bf1'
down_revision: Union[str, Sequence[str], None] = 'ff536b09e0a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('avaliacao', sa.Column('nome_avaliador', sa.String(length=150), nullable=True))
    op.add_column('avaliacao', sa.Column('tipo_avaliador', sa.String(length=20), nullable=True))
    op.add_column('avaliacao', sa.Column('projeto_avaliado', sa.String(length=150), nullable=True))
    op.add_column('avaliacao', sa.Column('escopo_avaliado_id', sa.Integer(), nullable=True))
    op.add_column('avaliacao', sa.Column('escopo_avaliado_outro', sa.String(length=150), nullable=True))
    op.create_foreign_key('fk_avaliacao_escopo_avaliado_id', 'avaliacao', 'escopo', ['escopo_avaliado_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # Nome explícito na FK acima: `drop_constraint(None, ...)` (o que o
    # autogenerate produz) falha no MySQL, precisa do nome de verdade.
    op.drop_constraint('fk_avaliacao_escopo_avaliado_id', 'avaliacao', type_='foreignkey')
    op.drop_column('avaliacao', 'escopo_avaliado_outro')
    op.drop_column('avaliacao', 'escopo_avaliado_id')
    op.drop_column('avaliacao', 'projeto_avaliado')
    op.drop_column('avaliacao', 'tipo_avaliador')
    op.drop_column('avaliacao', 'nome_avaliador')
    # ### end Alembic commands ###
