"""cargo_vira_posicao_permissao

Revision ID: 03ea41a273d0
Revises: 8d3962297df7
Create Date: 2026-08-07 03:39:53.463307

"""
from typing import Sequence, Union

from alembic import op
from src.utils.alembic_pg import nome_da_fk
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '03ea41a273d0'
down_revision: Union[str, Sequence[str], None] = '8d3962297df7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    if 'posicao_permissao' in sa.inspect(op.get_bind()).get_table_names():
        op.drop_table('posicao_permissao')
    op.create_table('posicao_permissao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('posicao', sa.Enum('diretor', 'gerente', 'coordenador', 'consultor', name='posicao_permissao_posicao'), nullable=False),
    sa.Column('pode_criar_projeto', sa.Boolean(), nullable=False),
    sa.Column('pode_editar_equipe', sa.Boolean(), nullable=False),
    sa.Column('pode_gerir_membros', sa.Boolean(), nullable=False),
    sa.Column('pode_marcar_kickoff', sa.Boolean(), nullable=False),
    sa.Column('pode_definir_cronograma', sa.Boolean(), nullable=False),
    sa.Column('pode_criar_tarefa', sa.Boolean(), nullable=False),
    sa.Column('pode_mover_editar_tarefa', sa.Boolean(), nullable=False),
    sa.Column('pode_ver_proprios_projetos', sa.Boolean(), nullable=False),
    sa.Column('pode_ver_monitoramento', sa.Boolean(), nullable=False),
    sa.Column('pode_administrar_desempenho', sa.Boolean(), nullable=False),
    sa.Column('pode_editar_formularios_desempenho', sa.Boolean(), nullable=False),
    sa.Column('pode_administrar_configuracoes', sa.Boolean(), nullable=False),
    sa.Column('pode_ver_todos_projetos', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('posicao')
    )
    op.create_index(op.f('ix_posicao_permissao_id'), 'posicao_permissao', ['id'], unique=False)

    # Seed com a tabela do §3 do briefing (as 9 originais) + as 4 extensões
    # que a plataforma ganhou depois, todas travadas em diretor por padrão —
    # editável na tela de Configurações depois desta migration.
    posicao_permissao = sa.table(
        'posicao_permissao',
        sa.column('posicao', sa.String),
        sa.column('pode_criar_projeto', sa.Boolean),
        sa.column('pode_editar_equipe', sa.Boolean),
        sa.column('pode_gerir_membros', sa.Boolean),
        sa.column('pode_marcar_kickoff', sa.Boolean),
        sa.column('pode_definir_cronograma', sa.Boolean),
        sa.column('pode_criar_tarefa', sa.Boolean),
        sa.column('pode_mover_editar_tarefa', sa.Boolean),
        sa.column('pode_ver_proprios_projetos', sa.Boolean),
        sa.column('pode_ver_monitoramento', sa.Boolean),
        sa.column('pode_administrar_desempenho', sa.Boolean),
        sa.column('pode_editar_formularios_desempenho', sa.Boolean),
        sa.column('pode_administrar_configuracoes', sa.Boolean),
        sa.column('pode_ver_todos_projetos', sa.Boolean),
    )
    op.bulk_insert(
        posicao_permissao,
        [
            {
                'posicao': 'diretor',
                'pode_criar_projeto': True,
                'pode_editar_equipe': True,
                'pode_gerir_membros': True,
                'pode_marcar_kickoff': True,
                'pode_definir_cronograma': True,
                'pode_criar_tarefa': True,
                'pode_mover_editar_tarefa': True,
                'pode_ver_proprios_projetos': True,
                'pode_ver_monitoramento': True,
                'pode_administrar_desempenho': True,
                'pode_editar_formularios_desempenho': True,
                'pode_administrar_configuracoes': True,
                'pode_ver_todos_projetos': True,
            },
            {
                'posicao': 'gerente',
                'pode_criar_projeto': True,
                'pode_editar_equipe': True,
                'pode_gerir_membros': False,
                'pode_marcar_kickoff': True,
                'pode_definir_cronograma': True,
                'pode_criar_tarefa': True,
                'pode_mover_editar_tarefa': True,
                'pode_ver_proprios_projetos': True,
                'pode_ver_monitoramento': True,
                'pode_administrar_desempenho': False,
                'pode_editar_formularios_desempenho': False,
                'pode_administrar_configuracoes': False,
                'pode_ver_todos_projetos': False,
            },
            {
                'posicao': 'coordenador',
                'pode_criar_projeto': False,
                'pode_editar_equipe': False,
                'pode_gerir_membros': False,
                'pode_marcar_kickoff': True,
                'pode_definir_cronograma': True,
                'pode_criar_tarefa': True,
                'pode_mover_editar_tarefa': True,
                'pode_ver_proprios_projetos': True,
                'pode_ver_monitoramento': False,
                'pode_administrar_desempenho': False,
                'pode_editar_formularios_desempenho': False,
                'pode_administrar_configuracoes': False,
                'pode_ver_todos_projetos': False,
            },
            {
                'posicao': 'consultor',
                'pode_criar_projeto': False,
                'pode_editar_equipe': False,
                'pode_gerir_membros': False,
                'pode_marcar_kickoff': True,
                'pode_definir_cronograma': False,
                'pode_criar_tarefa': True,
                'pode_mover_editar_tarefa': True,
                'pode_ver_proprios_projetos': True,
                'pode_ver_monitoramento': False,
                'pode_administrar_desempenho': False,
                'pode_editar_formularios_desempenho': False,
                'pode_administrar_configuracoes': False,
                'pode_ver_todos_projetos': False,
            },
        ],
    )

    # As duas FKs pra `cargo` têm que sair ANTES da tabela — senão o Postgres
    # recusa o DROP TABLE com "other objects depend on it".
    # ⚠ O nome da FK é gerado pelo banco e NÃO é portável: o Postgres a chama
    # de `configuracao_cargo_padrao_id_fkey`, o MySQL de `configuracao_ibfk_1`.
    # Cravar um dos dois quebra no outro com 1091. `nome_da_fk` pergunta.
    fk_config = nome_da_fk(op, 'configuracao', 'cargo_padrao_id')
    if fk_config:
        op.drop_constraint(fk_config, 'configuracao', type_='foreignkey')
    op.drop_column('configuracao', 'cargo_padrao_id')
    fk_usuario = nome_da_fk(op, 'usuario', 'cargo_id')
    if fk_usuario:
        op.drop_constraint(fk_usuario, 'usuario', type_='foreignkey')
    op.drop_column('usuario', 'cargo_id')
    op.drop_index(op.f('ix_cargo_id'), table_name='cargo')
    op.drop_table('cargo')
    # ### end Alembic commands ###
    # Nota: o autogenerate também detectou a mesma renomeação de índice de
    # `tarefa_coluna` de sempre — ruído antigo de portabilidade, sem relação
    # com esta migration, removido daqui de propósito.


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # `cargo_id` volta nullable (era NOT NULL): não há de onde backfillar —
    # `cargo` renasce vazia aqui embaixo, e esta migration não guarda o
    # vínculo antigo de ninguém. Downgrade de melhor esforço, não fiel.
    op.add_column('usuario', sa.Column('cargo_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('usuario_cargo_id_fkey'), 'usuario', 'cargo', ['cargo_id'], ['id'])
    op.add_column('configuracao', sa.Column('cargo_padrao_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('configuracao_cargo_padrao_id_fkey'), 'configuracao', 'cargo', ['cargo_padrao_id'], ['id'])
    op.create_table('cargo',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('pode_criar_projeto', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('pode_editar_equipe', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('pode_gerir_membros', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('pode_marcar_kickoff', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('pode_definir_cronograma', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('pode_criar_tarefa', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('pode_mover_editar_tarefa', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('pode_ver_proprios_projetos', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('pode_ver_monitoramento', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('pode_administrar_desempenho', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('pode_editar_formularios_desempenho', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('pode_administrar_configuracoes', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('pode_ver_todos_projetos', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('cargo_pkey'))
    )
    op.create_index(op.f('ix_cargo_id'), 'cargo', ['id'], unique=False)
    op.drop_index(op.f('ix_posicao_permissao_id'), table_name='posicao_permissao')
    op.drop_table('posicao_permissao')
    # ### end Alembic commands ###
