"""f6_cronograma_etapa_marco

Revision ID: 0b57c2b6b9aa
Revises: b6999b6d8ef5
Create Date: 2026-08-04 14:44:15.734507

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b57c2b6b9aa'
down_revision: Union[str, Sequence[str], None] = 'b6999b6d8ef5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cronograma_etapa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('projeto_escopo_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('cor', sa.String(length=7), nullable=False),
    sa.Column('data_inicio', sa.Date(), nullable=False),
    sa.Column('data_fim', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('planejada', 'em_andamento', 'concluida', 'cancelada', name='status_cronograma_etapa'), server_default='planejada', nullable=False),
    sa.Column('ordem', sa.SmallInteger(), server_default='0', nullable=False),
    sa.Column('criado_por', sa.Integer(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['criado_por'], ['usuario.id'], ),
    sa.ForeignKeyConstraint(['projeto_escopo_id'], ['projeto_escopo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cronograma_etapa_id'), 'cronograma_etapa', ['id'], unique=False)
    op.create_index(op.f('ix_cronograma_etapa_projeto_escopo_id'), 'cronograma_etapa', ['projeto_escopo_id'], unique=False)
    op.create_table('cronograma_marco',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('projeto_id', sa.Integer(), nullable=False),
    sa.Column('projeto_escopo_id', sa.Integer(), nullable=True),
    sa.Column('tipo', sa.Enum('reuniao_alinhamento', 'visita_presencial', name='tipo_cronograma_marco'), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('nota', sa.String(length=150), nullable=True),
    sa.Column('criado_por', sa.Integer(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['criado_por'], ['usuario.id'], ),
    sa.ForeignKeyConstraint(['projeto_escopo_id'], ['projeto_escopo.id'], ),
    sa.ForeignKeyConstraint(['projeto_id'], ['projeto.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cronograma_marco_id'), 'cronograma_marco', ['id'], unique=False)
    op.create_index(op.f('ix_cronograma_marco_projeto_escopo_id'), 'cronograma_marco', ['projeto_escopo_id'], unique=False)
    op.create_index(op.f('ix_cronograma_marco_projeto_id'), 'cronograma_marco', ['projeto_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cronograma_marco_projeto_id'), table_name='cronograma_marco')
    op.drop_index(op.f('ix_cronograma_marco_projeto_escopo_id'), table_name='cronograma_marco')
    op.drop_index(op.f('ix_cronograma_marco_id'), table_name='cronograma_marco')
    op.drop_table('cronograma_marco')
    op.drop_index(op.f('ix_cronograma_etapa_projeto_escopo_id'), table_name='cronograma_etapa')
    op.drop_index(op.f('ix_cronograma_etapa_id'), table_name='cronograma_etapa')
    op.drop_table('cronograma_etapa')
    # ### end Alembic commands ###
