"""remove_nota_corte_vagas_from_semestre

Revision ID: 135ffb8e855a
Revises: dbdc7370bada
Create Date: 2026-07-27 15:08:27.674551

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '135ffb8e855a'
down_revision: Union[str, Sequence[str], None] = 'dbdc7370bada'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('semestre', 'vagas_nucleo')
    op.drop_column('semestre', 'vagas_lideranca')
    op.drop_column('semestre', 'nota_corte')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('semestre', sa.Column('nota_corte', mysql.DECIMAL(precision=3, scale=2), nullable=False))
    op.add_column('semestre', sa.Column('vagas_lideranca', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('semestre', sa.Column('vagas_nucleo', mysql.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
