"""remove_pode_aprovar_reajuste

Revision ID: 1556cc590a06
Revises: 72a7a5145a5a
Create Date: 2026-08-06 18:48:49.266441

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '1556cc590a06'
down_revision: Union[str, Sequence[str], None] = '72a7a5145a5a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cargo', 'pode_aprovar_reajuste')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cargo', sa.Column('pode_aprovar_reajuste', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
