"""add_frente_equipe_usuario_frente_banca_frente

Revision ID: 1601abd6a525
Revises: 135ffb8e855a
Create Date: 2026-07-27 15:56:16.828595

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1601abd6a525'
down_revision: Union[str, Sequence[str], None] = '135ffb8e855a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('frente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_frente_id'), 'frente', ['id'], unique=False)
    op.create_table('usuario_frente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('frente_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['frente_id'], ['frente.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuario_frente_id'), 'usuario_frente', ['id'], unique=False)
    op.create_table('banca_frente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('banca_id', sa.Integer(), nullable=False),
    sa.Column('frente_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['banca_id'], ['banca.id'], ),
    sa.ForeignKeyConstraint(['frente_id'], ['frente.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_banca_frente_id'), 'banca_frente', ['id'], unique=False)
    op.create_table('equipe_projeto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('banca_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['banca_id'], ['banca.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_equipe_projeto_id'), 'equipe_projeto', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_equipe_projeto_id'), table_name='equipe_projeto')
    op.drop_table('equipe_projeto')
    op.drop_index(op.f('ix_banca_frente_id'), table_name='banca_frente')
    op.drop_table('banca_frente')
    op.drop_index(op.f('ix_usuario_frente_id'), table_name='usuario_frente')
    op.drop_table('usuario_frente')
    op.drop_index(op.f('ix_frente_id'), table_name='frente')
    op.drop_table('frente')
    # ### end Alembic commands ###
