"""add_anexo_proposta_projeto

Revision ID: 1d4a1b5924d7
Revises: d0b3af873672
Create Date: 2026-08-04 16:53:17.490958

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d4a1b5924d7'
down_revision: Union[str, Sequence[str], None] = 'd0b3af873672'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projeto', sa.Column('anexo_proposta_path', sa.String(length=255), nullable=True))
    op.add_column('projeto', sa.Column('anexo_proposta_nome', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projeto', 'anexo_proposta_nome')
    op.drop_column('projeto', 'anexo_proposta_path')
    # ### end Alembic commands ###
