"""f7c_tarefa_comentario

Revision ID: 1dcac039656c
Revises: 96bc443dfc15
Create Date: 2026-08-04 17:04:55.427846

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1dcac039656c'
down_revision: Union[str, Sequence[str], None] = '96bc443dfc15'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tarefa_comentario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tarefa_id', sa.Integer(), nullable=False),
    sa.Column('autor_id', sa.Integer(), nullable=False),
    sa.Column('texto', sa.Text(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['autor_id'], ['usuario.id'], ),
    sa.ForeignKeyConstraint(['tarefa_id'], ['tarefa.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tarefa_comentario_id'), 'tarefa_comentario', ['id'], unique=False)
    op.create_index(op.f('ix_tarefa_comentario_tarefa_id'), 'tarefa_comentario', ['tarefa_id'], unique=False)
    # A ordem importa: `tarefa.coluna_id` tem uma FK que sempre precisa de um
    # índice de apoio. Criar o novo antes de derrubar o antigo evita o
    # instante sem nenhum, que o MySQL recusa (erro 1553).
    op.create_index(op.f('ix_tarefa_coluna_id'), 'tarefa', ['coluna_id'], unique=False)
    op.drop_index(op.f('ix_tarefa_coluna_id_fk'), table_name='tarefa')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_tarefa_coluna_id_fk'), 'tarefa', ['coluna_id'], unique=False)
    op.drop_index(op.f('ix_tarefa_coluna_id'), table_name='tarefa')
    op.drop_index(op.f('ix_tarefa_comentario_tarefa_id'), table_name='tarefa_comentario')
    op.drop_index(op.f('ix_tarefa_comentario_id'), table_name='tarefa_comentario')
    op.drop_table('tarefa_comentario')
    # ### end Alembic commands ###
