"""tornar_data_hora_obrigatorio_em_banca

Revision ID: 1f5ee66b79a2
Revises: 6958bbb5b6c0
Create Date: 2026-07-28 20:09:00.530980

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '1f5ee66b79a2'
down_revision: Union[str, Sequence[str], None] = '6958bbb5b6c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('banca', 'data_hora',
               existing_type=mysql.DATETIME(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('banca', 'data_hora',
               existing_type=mysql.DATETIME(),
               nullable=True)
    # ### end Alembic commands ###
