"""desempenho_pdi_item_e_envio_por_item

Revision ID: 21adfe0d3a5c
Revises: 6172519c6fab
Create Date: 2026-08-06 15:04:24.811123

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '21adfe0d3a5c'
down_revision: Union[str, Sequence[str], None] = '6172519c6fab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('desempenho_pdi_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pasta_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('tipo_arquivo', sa.Enum('documento', 'foto', 'qualquer', name='desempenho_pdi_item_tipo_arquivo'), server_default='qualquer', nullable=False),
    sa.Column('ordem', sa.Integer(), server_default='0', nullable=False),
    sa.Column('criado_em', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['pasta_id'], ['desempenho_pdi_pasta.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_desempenho_pdi_item_id'), 'desempenho_pdi_item', ['id'], unique=False)
    op.create_index(op.f('ix_desempenho_pdi_item_pasta_id'), 'desempenho_pdi_item', ['pasta_id'], unique=False)

    # Um item padrão por pasta já existente — sem isso a pasta ficaria sem
    # nenhum documento exigível até a diretoria configurar a checklist em
    # `PainelPdi`. `desempenho_pdi_envio` está vazia neste ponto (feature
    # ainda não tinha nenhum envio real), então dá pra trocar pasta_id por
    # item_id como NOT NULL direto, sem precisar de backfill.
    bind = op.get_bind()
    pasta_ids = [row[0] for row in bind.execute(sa.text("SELECT id FROM desempenho_pdi_pasta")).fetchall()]
    if pasta_ids:
        item_table = sa.table(
            'desempenho_pdi_item',
            sa.column('pasta_id', sa.Integer),
            sa.column('nome', sa.String),
            sa.column('tipo_arquivo', sa.String),
            sa.column('ordem', sa.Integer),
        )
        op.bulk_insert(
            item_table,
            [{"pasta_id": pid, "nome": "Relatório", "tipo_arquivo": "qualquer", "ordem": 1} for pid in pasta_ids],
        )

    op.add_column('desempenho_pdi_envio', sa.Column('item_id', sa.Integer(), nullable=False))
    # A FK de pasta_id precisa sair ANTES do unique — o MySQL recusa dropar um
    # índice que uma FK ainda usa por baixo (erro 1553). Dropar a FK já leva
    # junto o índice não-único que ela usava (`ix_..._pasta_id`), por isso
    # só o `drop_index` do unique continua explícito abaixo.
    op.drop_constraint(op.f('desempenho_pdi_envio_ibfk_3'), 'desempenho_pdi_envio', type_='foreignkey')
    op.drop_index(op.f('uq_pdi_envio_pasta_mentorado'), table_name='desempenho_pdi_envio')
    op.create_index(op.f('ix_desempenho_pdi_envio_item_id'), 'desempenho_pdi_envio', ['item_id'], unique=False)
    op.create_unique_constraint('uq_pdi_envio_item_mentorado', 'desempenho_pdi_envio', ['item_id', 'mentorado_id'])
    op.create_foreign_key(None, 'desempenho_pdi_envio', 'desempenho_pdi_item', ['item_id'], ['id'])
    op.drop_column('desempenho_pdi_envio', 'pasta_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('desempenho_pdi_envio', sa.Column('pasta_id', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'desempenho_pdi_envio', type_='foreignkey')
    op.create_foreign_key(op.f('desempenho_pdi_envio_ibfk_3'), 'desempenho_pdi_envio', 'desempenho_pdi_pasta', ['pasta_id'], ['id'])
    op.drop_constraint('uq_pdi_envio_item_mentorado', 'desempenho_pdi_envio', type_='unique')
    op.drop_index(op.f('ix_desempenho_pdi_envio_item_id'), table_name='desempenho_pdi_envio')
    op.create_index(op.f('uq_pdi_envio_pasta_mentorado'), 'desempenho_pdi_envio', ['pasta_id', 'mentorado_id'], unique=True)
    op.create_index(op.f('ix_desempenho_pdi_envio_pasta_id'), 'desempenho_pdi_envio', ['pasta_id'], unique=False)
    op.drop_column('desempenho_pdi_envio', 'item_id')
    op.drop_index(op.f('ix_desempenho_pdi_item_pasta_id'), table_name='desempenho_pdi_item')
    op.drop_index(op.f('ix_desempenho_pdi_item_id'), table_name='desempenho_pdi_item')
    op.drop_table('desempenho_pdi_item')
    # ### end Alembic commands ###
