"""pedido de excecao de choque de banca

Revision ID: 272d44505958
Revises: c9d2f47b6103
Create Date: 2026-08-12 20:50:20.725540

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '272d44505958'
down_revision: Union[str, Sequence[str], None] = 'c9d2f47b6103'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('banca_excecao_choque_solicitacao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('projeto_escopo_id', sa.Integer(), nullable=False),
    sa.Column('banca_id', sa.Integer(), nullable=True),
    sa.Column('data_hora_pretendida', sa.DateTime(), nullable=False),
    sa.Column('banca_conflitante_id', sa.Integer(), nullable=True),
    sa.Column('justificativa', sa.String(length=500), nullable=False),
    sa.Column('status', sa.Enum('pendente', 'aprovada', 'recusada', name='status_excecao_choque'), server_default='pendente', nullable=False),
    sa.Column('solicitado_por', sa.Integer(), nullable=False),
    sa.Column('respondido_por', sa.Integer(), nullable=True),
    sa.Column('resposta', sa.String(length=500), nullable=True),
    sa.Column('criado_em', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('respondido_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['banca_conflitante_id'], ['banca.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['banca_id'], ['banca.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['projeto_escopo_id'], ['projeto_escopo.id'], ),
    sa.ForeignKeyConstraint(['respondido_por'], ['usuario.id'], ),
    sa.ForeignKeyConstraint(['solicitado_por'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_banca_excecao_choque_solicitacao_banca_id'), 'banca_excecao_choque_solicitacao', ['banca_id'], unique=False)
    op.create_index(op.f('ix_banca_excecao_choque_solicitacao_data_hora_pretendida'), 'banca_excecao_choque_solicitacao', ['data_hora_pretendida'], unique=False)
    op.create_index(op.f('ix_banca_excecao_choque_solicitacao_id'), 'banca_excecao_choque_solicitacao', ['id'], unique=False)
    op.create_index(op.f('ix_banca_excecao_choque_solicitacao_projeto_escopo_id'), 'banca_excecao_choque_solicitacao', ['projeto_escopo_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_banca_excecao_choque_solicitacao_projeto_escopo_id'), table_name='banca_excecao_choque_solicitacao')
    op.drop_index(op.f('ix_banca_excecao_choque_solicitacao_id'), table_name='banca_excecao_choque_solicitacao')
    op.drop_index(op.f('ix_banca_excecao_choque_solicitacao_data_hora_pretendida'), table_name='banca_excecao_choque_solicitacao')
    op.drop_index(op.f('ix_banca_excecao_choque_solicitacao_banca_id'), table_name='banca_excecao_choque_solicitacao')
    op.drop_table('banca_excecao_choque_solicitacao')
    # ### end Alembic commands ###
