"""F1 base do semestre: dia_nao_letivo, semestre.status, frente.piso_banca, escopo.frente_id

Revision ID: 41718600bc82
Revises: 9a017078a712
Create Date: 2026-08-04 10:04:03.393552

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '41718600bc82'
down_revision: Union[str, Sequence[str], None] = '9a017078a712'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dia_nao_letivo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('semestre_id', sa.Integer(), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('tipo', sa.Enum('feriado', 'prova', 'recesso', name='tipo_dia_nao_letivo'), nullable=False),
    sa.Column('descricao', sa.String(length=150), nullable=True),
    sa.ForeignKeyConstraint(['semestre_id'], ['semestre.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('semestre_id', 'data', name='uq_dia_nao_letivo_semestre_data')
    )
    op.create_index(op.f('ix_dia_nao_letivo_data'), 'dia_nao_letivo', ['data'], unique=False)
    op.create_index(op.f('ix_dia_nao_letivo_id'), 'dia_nao_letivo', ['id'], unique=False)
    op.create_index(op.f('ix_dia_nao_letivo_semestre_id'), 'dia_nao_letivo', ['semestre_id'], unique=False)
    op.add_column('escopo', sa.Column('frente_id', sa.Integer(), nullable=True))
    op.add_column('escopo', sa.Column('ativo', sa.Boolean(), server_default='1', nullable=False))
    op.create_index(op.f('ix_escopo_frente_id'), 'escopo', ['frente_id'], unique=False)
    # FK nomeada: o autogenerate deixa None, e o MySQL não consegue derrubar
    # uma constraint anônima no downgrade.
    op.create_foreign_key('fk_escopo_frente', 'escopo', 'frente', ['frente_id'], ['id'])
    op.add_column('frente', sa.Column('ativa', sa.Boolean(), server_default='1', nullable=False))
    op.add_column('frente', sa.Column('piso_banca', sa.Integer(), server_default='1', nullable=False))
    # No MySQL o ENUM nasce junto com a coluna. No Postgres é um TYPE à parte
    # — `add_column` numa tabela já existente não cria o type sozinho (só
    # `create_table` faz isso), então precisa criar antes, explícito.
    # `checkfirst=True` faz o `.create()` ser um no-op no MySQL.
    status_semestre = sa.Enum('ativa', 'arquivada', name='status_semestre')
    status_semestre.create(op.get_bind(), checkfirst=True)
    op.add_column('semestre', sa.Column('status', status_semestre, server_default='ativa', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_column('semestre', 'status')
    op.drop_column('frente', 'piso_banca')
    op.drop_column('frente', 'ativa')
    # A FK sai antes do índice: o MySQL recusa dropar um índice de que uma FK
    # ainda depende (erro 1553).
    op.drop_constraint('fk_escopo_frente', 'escopo', type_='foreignkey')
    op.drop_index(op.f('ix_escopo_frente_id'), table_name='escopo')
    op.drop_column('escopo', 'ativo')
    op.drop_column('escopo', 'frente_id')
    # `drop_table` já leva os índices da tabela junto — dropá-los antes é o que
    # quebra a reversibilidade no MySQL.
    op.drop_table('dia_nao_letivo')
