"""remove_status_from_banca_calculado_dinamicamente

Revision ID: 43658693c11d
Revises: b210b2233a5c
Create Date: 2026-07-28 17:52:36.197869

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '43658693c11d'
down_revision: Union[str, Sequence[str], None] = 'b210b2233a5c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('banca', 'status')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('banca', sa.Column('status', mysql.VARCHAR(length=30), nullable=False))
    # ### end Alembic commands ###
