"""add_situacao_carga

Revision ID: 4fdf0a86da7e
Revises: 8c6ba356d298
Create Date: 2026-08-06 00:17:39.524968

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4fdf0a86da7e'
down_revision: Union[str, Sequence[str], None] = '8c6ba356d298'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('situacao_carga',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('papel', sa.Enum('coordenador', 'consultor', name='papel_situacao_carga'), nullable=False),
    sa.Column('nome', sa.String(length=60), nullable=False),
    sa.Column('min_projetos', sa.Integer(), nullable=False),
    sa.Column('tom', sa.Enum('ok', 'atencao', 'alerta', 'neutro', name='tom_situacao_carga'), server_default='neutro', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('papel', 'min_projetos', name='uq_situacao_papel_minimo')
    )
    op.create_index(op.f('ix_situacao_carga_id'), 'situacao_carga', ['id'], unique=False)
    op.create_index(op.f('ix_situacao_carga_papel'), 'situacao_carga', ['papel'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_situacao_carga_papel'), table_name='situacao_carga')
    op.drop_index(op.f('ix_situacao_carga_id'), table_name='situacao_carga')
    op.drop_table('situacao_carga')
    # ### end Alembic commands ###
