"""add_semestre_graduacao_usuario

Revision ID: 5c96b67076b0
Revises: d81e5a2c9f37
Create Date: 2026-08-06 12:04:35.305343

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c96b67076b0'
down_revision: Union[str, Sequence[str], None] = 'd81e5a2c9f37'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuario', sa.Column('semestre_graduacao', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuario', 'semestre_graduacao')
    # ### end Alembic commands ###
