"""lideranca_minima_por_frente_configuracao

Revision ID: 5f69087982a7
Revises: 3ae5c0c244c0
Create Date: 2026-08-06 20:25:49.671033

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f69087982a7'
down_revision: Union[str, Sequence[str], None] = '3ae5c0c244c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('configuracao', sa.Column('lideranca_minima_por_frente', sa.Integer(), server_default='1', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('configuracao', 'lideranca_minima_por_frente')
    # ### end Alembic commands ###
