"""add_pdi_notificacao_tipos

Revision ID: 6172519c6fab
Revises: 7d0730fbe457
Create Date: 2026-08-06 14:18:41.219873

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

from src.utils.alembic_pg import redefinir_enum_postgres

# revision identifiers, used by Alembic.
revision: str = '6172519c6fab'
down_revision: Union[str, Sequence[str], None] = '7d0730fbe457'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    if op.get_bind().dialect.name == 'postgresql':
        redefinir_enum_postgres(
            op, 'notificacao', 'tipo', 'tipo_notificacao',
            ['alocado_em_projeto', 'entrega_registrada', 'banca_remarcada', 'entrega_alterada', 'escalacao_banca', 'troca_banca', 'avaliacao_pendente', 'banca_aviso', 'lote_desempenho_aberto', 'pdi_prazo_proximo', 'pdi_prazo_vencido', 'kickoff_pendente', 'tarefa_vencida', 'banca_nao_marcada', 'projeto_sem_reuniao', 'banca_hoje'],
        )
    else:
        op.alter_column('notificacao', 'tipo',
                   existing_type=mysql.ENUM('alocado_em_projeto', 'entrega_registrada', 'escalacao_banca', 'troca_banca', 'avaliacao_pendente', 'banca_aviso', 'kickoff_pendente', 'tarefa_vencida', 'banca_nao_marcada', 'projeto_sem_reuniao', 'banca_hoje', 'banca_remarcada', 'entrega_alterada', 'lote_desempenho_aberto'),
                   type_=sa.Enum('alocado_em_projeto', 'entrega_registrada', 'banca_remarcada', 'entrega_alterada', 'escalacao_banca', 'troca_banca', 'avaliacao_pendente', 'banca_aviso', 'lote_desempenho_aberto', 'pdi_prazo_proximo', 'pdi_prazo_vencido', 'kickoff_pendente', 'tarefa_vencida', 'banca_nao_marcada', 'projeto_sem_reuniao', 'banca_hoje', name='tipo_notificacao'),
                   existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('notificacao', 'tipo',
               existing_type=sa.Enum('alocado_em_projeto', 'entrega_registrada', 'banca_remarcada', 'entrega_alterada', 'escalacao_banca', 'troca_banca', 'avaliacao_pendente', 'banca_aviso', 'lote_desempenho_aberto', 'pdi_prazo_proximo', 'pdi_prazo_vencido', 'kickoff_pendente', 'tarefa_vencida', 'banca_nao_marcada', 'projeto_sem_reuniao', 'banca_hoje', name='tipo_notificacao'),
               type_=mysql.ENUM('alocado_em_projeto', 'entrega_registrada', 'escalacao_banca', 'troca_banca', 'avaliacao_pendente', 'banca_aviso', 'kickoff_pendente', 'tarefa_vencida', 'banca_nao_marcada', 'projeto_sem_reuniao', 'banca_hoje', 'banca_remarcada', 'entrega_alterada', 'lote_desempenho_aberto'),
               existing_nullable=False)
    # ### end Alembic commands ###
