"""remove_nota_final_from_banca_calculado_dinamicamente

Revision ID: 6958bbb5b6c0
Revises: 43658693c11d
Create Date: 2026-07-28 18:35:43.975145

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '6958bbb5b6c0'
down_revision: Union[str, Sequence[str], None] = '43658693c11d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('banca', 'nota_final')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('banca', sa.Column('nota_final', mysql.DECIMAL(precision=3, scale=2), nullable=True))
    # ### end Alembic commands ###
