"""reverte_reajuste_cronograma

Revision ID: 72a7a5145a5a
Revises: 97c0c770e8ae
Create Date: 2026-08-06 18:39:26.590445

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '72a7a5145a5a'
down_revision: Union[str, Sequence[str], None] = '97c0c770e8ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # DROP TABLE já leva os índices (inclusive o que a FK usa por baixo) —
    # dropar antes bate no mesmo erro 1553 de outras migrações deste repo.
    op.drop_table('cronograma_reajuste_solicitacao')

    # Sem isso, o ALTER de enum abaixo falha (ou pior, trunca) qualquer linha
    # que já use 'reajuste_solicitado'/'reajuste_respondido' — o recurso
    # inteiro foi removido, essas notificações não têm mais pra onde apontar.
    op.execute("DELETE FROM notificacao WHERE tipo IN ('reajuste_solicitado', 'reajuste_respondido')")

    op.alter_column('notificacao', 'tipo',
               existing_type=mysql.ENUM('alocado_em_projeto', 'entrega_registrada', 'banca_remarcada', 'entrega_alterada', 'escalacao_banca', 'troca_banca', 'avaliacao_pendente', 'banca_aviso', 'lote_desempenho_aberto', 'pdi_prazo_proximo', 'pdi_prazo_vencido', 'reajuste_solicitado', 'reajuste_respondido', 'kickoff_pendente', 'tarefa_vencida', 'banca_nao_marcada', 'projeto_sem_reuniao', 'banca_hoje'),
               type_=sa.Enum('alocado_em_projeto', 'entrega_registrada', 'banca_remarcada', 'entrega_alterada', 'escalacao_banca', 'troca_banca', 'avaliacao_pendente', 'banca_aviso', 'lote_desempenho_aberto', 'pdi_prazo_proximo', 'pdi_prazo_vencido', 'kickoff_pendente', 'tarefa_vencida', 'banca_nao_marcada', 'projeto_sem_reuniao', 'banca_hoje', name='tipo_notificacao'),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('notificacao', 'tipo',
               existing_type=sa.Enum('alocado_em_projeto', 'entrega_registrada', 'banca_remarcada', 'entrega_alterada', 'escalacao_banca', 'troca_banca', 'avaliacao_pendente', 'banca_aviso', 'lote_desempenho_aberto', 'pdi_prazo_proximo', 'pdi_prazo_vencido', 'kickoff_pendente', 'tarefa_vencida', 'banca_nao_marcada', 'projeto_sem_reuniao', 'banca_hoje', name='tipo_notificacao'),
               type_=mysql.ENUM('alocado_em_projeto', 'entrega_registrada', 'banca_remarcada', 'entrega_alterada', 'escalacao_banca', 'troca_banca', 'avaliacao_pendente', 'banca_aviso', 'lote_desempenho_aberto', 'pdi_prazo_proximo', 'pdi_prazo_vencido', 'reajuste_solicitado', 'reajuste_respondido', 'kickoff_pendente', 'tarefa_vencida', 'banca_nao_marcada', 'projeto_sem_reuniao', 'banca_hoje'),
               existing_nullable=False)
    op.create_table('cronograma_reajuste_solicitacao',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('projeto_escopo_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('solicitado_por', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('motivo', mysql.VARCHAR(length=500), nullable=False),
    sa.Column('status', mysql.ENUM('pendente', 'aprovado', 'rejeitado'), server_default=sa.text("'pendente'"), nullable=False),
    sa.Column('respondido_por', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('resposta_justificativa', mysql.VARCHAR(length=500), nullable=True),
    sa.Column('criado_em', mysql.DATETIME(), server_default=sa.text('(now())'), nullable=False),
    sa.Column('respondido_em', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['projeto_escopo_id'], ['projeto_escopo.id'], name=op.f('cronograma_reajuste_solicitacao_ibfk_1')),
    sa.ForeignKeyConstraint(['respondido_por'], ['usuario.id'], name=op.f('cronograma_reajuste_solicitacao_ibfk_2')),
    sa.ForeignKeyConstraint(['solicitado_por'], ['usuario.id'], name=op.f('cronograma_reajuste_solicitacao_ibfk_3')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_cronograma_reajuste_solicitacao_projeto_escopo_id'), 'cronograma_reajuste_solicitacao', ['projeto_escopo_id'], unique=False)
    op.create_index(op.f('ix_cronograma_reajuste_solicitacao_id'), 'cronograma_reajuste_solicitacao', ['id'], unique=False)
    # ### end Alembic commands ###
