"""notificacao_e_solicitacao_troca

Revision ID: 73fcb381a784
Revises: 767bc82386f4
Create Date: 2026-08-05 17:13:30.698612

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '73fcb381a784'
down_revision: Union[str, Sequence[str], None] = '767bc82386f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notificacao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('mensagem', sa.String(length=255), nullable=False),
    sa.Column('banca_id', sa.Integer(), nullable=True),
    sa.Column('lida', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['banca_id'], ['banca.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notificacao_id'), 'notificacao', ['id'], unique=False)
    op.create_table('solicitacao_troca',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('banca_id', sa.Integer(), nullable=False),
    sa.Column('usuario_original_id', sa.Integer(), nullable=False),
    sa.Column('candidatura_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('pendente', 'confirmada', 'cancelada', name='status_solicitacao_troca'), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('confirmada_por', sa.Integer(), nullable=True),
    sa.Column('confirmada_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['banca_id'], ['banca.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['candidatura_id'], ['candidatura.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['confirmada_por'], ['usuario.id'], ),
    sa.ForeignKeyConstraint(['usuario_original_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_solicitacao_troca_id'), 'solicitacao_troca', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_solicitacao_troca_id'), table_name='solicitacao_troca')
    op.drop_table('solicitacao_troca')
    op.drop_index(op.f('ix_notificacao_id'), table_name='notificacao')
    op.drop_table('notificacao')
    # ### end Alembic commands ###
