"""banca_piso_minimo_override

Revision ID: 767bc82386f4
Revises: d3a41fddc68d
Create Date: 2026-08-05 16:49:28.092989

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '767bc82386f4'
down_revision: Union[str, Sequence[str], None] = 'd3a41fddc68d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('banca', sa.Column('piso_minimo_override', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('banca', 'piso_minimo_override')
    # ### end Alembic commands ###
