"""desempenho_pdi_pasta_e_envio

Revision ID: 7d0730fbe457
Revises: 388158bb44e6
Create Date: 2026-08-06 14:09:07.264176

"""
from datetime import date, timedelta
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d0730fbe457'
down_revision: Union[str, Sequence[str], None] = '388158bb44e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('desempenho_pdi_pasta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('tipo', sa.Enum('inicial', 'encontro', name='desempenho_pdi_pasta_tipo'), nullable=False),
    sa.Column('prazo', sa.Date(), nullable=False),
    sa.Column('ordem', sa.Integer(), server_default='0', nullable=False),
    sa.Column('criado_em', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_desempenho_pdi_pasta_id'), 'desempenho_pdi_pasta', ['id'], unique=False)
    op.create_table('desempenho_pdi_envio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pasta_id', sa.Integer(), nullable=False),
    sa.Column('mentorado_id', sa.Integer(), nullable=False),
    sa.Column('enviado_por', sa.Integer(), nullable=False),
    sa.Column('arquivo_path', sa.String(length=255), nullable=False),
    sa.Column('arquivo_nome', sa.String(length=255), nullable=False),
    sa.Column('enviado_em', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['enviado_por'], ['usuario.id'], ),
    sa.ForeignKeyConstraint(['mentorado_id'], ['usuario.id'], ),
    sa.ForeignKeyConstraint(['pasta_id'], ['desempenho_pdi_pasta.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pasta_id', 'mentorado_id', name='uq_pdi_envio_pasta_mentorado')
    )
    op.create_index(op.f('ix_desempenho_pdi_envio_id'), 'desempenho_pdi_envio', ['id'], unique=False)
    op.create_index(op.f('ix_desempenho_pdi_envio_mentorado_id'), 'desempenho_pdi_envio', ['mentorado_id'], unique=False)
    op.create_index(op.f('ix_desempenho_pdi_envio_pasta_id'), 'desempenho_pdi_envio', ['pasta_id'], unique=False)
    # ### end Alembic commands ###

    # As 3 pastas padrão, pra tela de PDI não nascer vazia — prazos são só um
    # ponto de partida, a diretoria edita depois em `PainelPdi`.
    pasta_table = sa.table(
        'desempenho_pdi_pasta',
        sa.column('nome', sa.String),
        sa.column('tipo', sa.String),
        sa.column('prazo', sa.Date),
        sa.column('ordem', sa.Integer),
    )
    hoje = date.today()
    op.bulk_insert(
        pasta_table,
        [
            {"nome": "PDI inicial", "tipo": "inicial", "prazo": hoje + timedelta(days=14), "ordem": 1},
            {"nome": "Encontro 1", "tipo": "encontro", "prazo": hoje + timedelta(days=30), "ordem": 2},
            {"nome": "Encontro 2", "tipo": "encontro", "prazo": hoje + timedelta(days=60), "ordem": 3},
        ],
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_desempenho_pdi_envio_pasta_id'), table_name='desempenho_pdi_envio')
    op.drop_index(op.f('ix_desempenho_pdi_envio_mentorado_id'), table_name='desempenho_pdi_envio')
    op.drop_index(op.f('ix_desempenho_pdi_envio_id'), table_name='desempenho_pdi_envio')
    op.drop_table('desempenho_pdi_envio')
    op.drop_index(op.f('ix_desempenho_pdi_pasta_id'), table_name='desempenho_pdi_pasta')
    op.drop_table('desempenho_pdi_pasta')
    # ### end Alembic commands ###
