"""F2 perfis: usuario.posicao e status, usuario_posicao_historico

Revision ID: 8b6e0c9ca6d9
Revises: 41718600bc82
Create Date: 2026-08-04 10:20:56.846076

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b6e0c9ca6d9'
down_revision: Union[str, Sequence[str], None] = '41718600bc82'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuario_posicao_historico',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('posicao', sa.Enum('diretor', 'gerente', 'coordenador', 'consultor', name='posicao_historico'), nullable=False),
    sa.Column('semestre_id', sa.Integer(), nullable=True),
    sa.Column('alterado_por', sa.Integer(), nullable=True),
    sa.Column('alterado_em', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['alterado_por'], ['usuario.id'], ),
    sa.ForeignKeyConstraint(['semestre_id'], ['semestre.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuario_posicao_historico_id'), 'usuario_posicao_historico', ['id'], unique=False)
    op.create_index(op.f('ix_usuario_posicao_historico_usuario_id'), 'usuario_posicao_historico', ['usuario_id'], unique=False)
    op.add_column('usuario', sa.Column('posicao', sa.Enum('diretor', 'gerente', 'coordenador', 'consultor', name='posicao_usuario'), server_default='consultor', nullable=False))
    op.add_column('usuario', sa.Column('status', sa.Enum('ativo', 'ex_membro', 'desligado', name='status_usuario'), server_default='ativo', nullable=False))
    # ### end Alembic commands ###

    # Backfill: quem já estava desativado vira ex_membro, não fica como "ativo".
    # `desligado` é decisão humana e não dá para inferir do booleano — quem foi
    # desligado de verdade a diretoria remarca pela tela de Membros.
    op.execute("UPDATE usuario SET status = 'ex_membro' WHERE ativo = 0")

    # Quem já podia gerenciar cargos é a diretoria; o resto começa consultor e a
    # diretoria ajusta na virada.
    op.execute(
        """
        UPDATE usuario u
        JOIN cargo c ON c.id = u.cargo_id
        SET u.posicao = 'diretor'
        WHERE c.pode_gerenciar_cargos = 1
        """
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_column('usuario', 'status')
    op.drop_column('usuario', 'posicao')
    # NÃO dropar os índices antes da tabela: o MySQL recusa remover um índice
    # de que uma FK depende (erro 1553), e como o DDL dele não é transacional a
    # migration morre no meio, deixando o banco fora de sincronia com o alembic.
    # `drop_table` já leva os índices junto.
    op.drop_table('usuario_posicao_historico')
