"""projeto_justificativa_atraso

Revision ID: 9206e864f0b2
Revises: da56fec9a08b
Create Date: 2026-08-06 16:57:22.641129

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9206e864f0b2'
down_revision: Union[str, Sequence[str], None] = 'da56fec9a08b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projeto_justificativa_atraso',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('projeto_id', sa.Integer(), nullable=False),
    sa.Column('projeto_escopo_id', sa.Integer(), nullable=True),
    sa.Column('texto', sa.Text(), nullable=False),
    sa.Column('registrado_por', sa.Integer(), nullable=False),
    sa.Column('registrado_em', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['projeto_escopo_id'], ['projeto_escopo.id'], ),
    sa.ForeignKeyConstraint(['projeto_id'], ['projeto.id'], ),
    sa.ForeignKeyConstraint(['registrado_por'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projeto_justificativa_atraso_id'), 'projeto_justificativa_atraso', ['id'], unique=False)
    op.create_index(op.f('ix_projeto_justificativa_atraso_projeto_id'), 'projeto_justificativa_atraso', ['projeto_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_projeto_justificativa_atraso_projeto_id'), table_name='projeto_justificativa_atraso')
    op.drop_index(op.f('ix_projeto_justificativa_atraso_id'), table_name='projeto_justificativa_atraso')
    op.drop_table('projeto_justificativa_atraso')
    # ### end Alembic commands ###
