"""cargo_permissoes_estendidas

Revision ID: 97c0c770e8ae
Revises: 9a4f6184cba9
Create Date: 2026-08-06 17:35:40.069316

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '97c0c770e8ae'
down_revision: Union[str, Sequence[str], None] = '9a4f6184cba9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust (server_default
    # adicionado à mão: a tabela já tem linhas, NOT NULL sem default falha). ###
    op.add_column(
        'cargo',
        sa.Column('pode_administrar_desempenho', sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    op.add_column(
        'cargo',
        sa.Column('pode_editar_formularios_desempenho', sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    op.add_column(
        'cargo', sa.Column('pode_ver_nucleo', sa.Boolean(), nullable=False, server_default=sa.false())
    )
    op.add_column(
        'cargo',
        sa.Column('pode_administrar_configuracoes', sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    # ### end Alembic commands ###

    # Preserva EXATAMENTE o acesso de hoje (travado por posição) na virada
    # pra caixa de cargo — ninguém ganha nem perde acesso só por causa desta
    # migração. Os nomes batem com o seed (`scripts/seed.py`); em bancos que
    # renomearam os cargos, ajustar manualmente depois.
    cargo = sa.table(
        'cargo',
        sa.column('nome', sa.String),
        sa.column('pode_administrar_desempenho', sa.Boolean),
        sa.column('pode_editar_formularios_desempenho', sa.Boolean),
        sa.column('pode_ver_nucleo', sa.Boolean),
        sa.column('pode_administrar_configuracoes', sa.Boolean),
    )
    # Admin e Diretor de Projetos: tinham tudo (posição diretor destrava as 4).
    op.execute(
        cargo.update()
        .where(cargo.c.nome.in_(["Admin", "Diretor de Projetos"]))
        .values(
            pode_administrar_desempenho=True,
            pode_editar_formularios_desempenho=True,
            pode_ver_nucleo=True,
            pode_administrar_configuracoes=True,
        )
    )
    # Gerente de Frente: tinha o painel de desempenho (era diretor+gerente),
    # mas não formulários/núcleo/config (eram só diretor).
    op.execute(
        cargo.update()
        .where(cargo.c.nome == "Gerente de Frente")
        .values(pode_administrar_desempenho=True)
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cargo', 'pode_administrar_configuracoes')
    op.drop_column('cargo', 'pode_ver_nucleo')
    op.drop_column('cargo', 'pode_editar_formularios_desempenho')
    op.drop_column('cargo', 'pode_administrar_desempenho')
    # ### end Alembic commands ###
