"""add_senha_hash_usuario_e_cargo_padrao_configuracao

Revision ID: 9a017078a712
Revises: a4f99ec3dfcb
Create Date: 2026-07-30 20:14:39.352928

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a017078a712'
down_revision: Union[str, Sequence[str], None] = 'a4f99ec3dfcb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('configuracao', sa.Column('cargo_padrao_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'configuracao', 'cargo', ['cargo_padrao_id'], ['id'])
    op.add_column('usuario', sa.Column('senha_hash', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_column('usuario', 'senha_hash')

    # O autogenerate deixou `drop_constraint(None, ...)` aqui, e passar None
    # levanta AssertionError — o que travava `alembic downgrade` em toda a
    # cadeia a partir desta revisão. Como o upgrade criou a FK sem nome, quem
    # nomeou foi o MySQL (configuracao_ibfk_N); então descobrimos o nome real
    # em vez de chutar.
    conexao = op.get_bind()
    inspector = sa.inspect(conexao)
    for fk in inspector.get_foreign_keys('configuracao'):
        if fk['constrained_columns'] == ['cargo_padrao_id']:
            op.drop_constraint(fk['name'], 'configuracao', type_='foreignkey')
            break

    op.drop_column('configuracao', 'cargo_padrao_id')
