"""cronograma_reajuste_solicitacao

Revision ID: 9a4f6184cba9
Revises: d9185a5df397
Create Date: 2026-08-06 16:36:45.375661

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '9a4f6184cba9'
down_revision: Union[str, Sequence[str], None] = 'd9185a5df397'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cronograma_reajuste_solicitacao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('projeto_escopo_id', sa.Integer(), nullable=False),
    sa.Column('solicitado_por', sa.Integer(), nullable=False),
    sa.Column('motivo', sa.String(length=500), nullable=False),
    sa.Column('status', sa.Enum('pendente', 'aprovado', 'rejeitado', name='status_reajuste_cronograma'), server_default='pendente', nullable=False),
    sa.Column('respondido_por', sa.Integer(), nullable=True),
    sa.Column('resposta_justificativa', sa.String(length=500), nullable=True),
    sa.Column('criado_em', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('respondido_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['projeto_escopo_id'], ['projeto_escopo.id'], ),
    sa.ForeignKeyConstraint(['respondido_por'], ['usuario.id'], ),
    sa.ForeignKeyConstraint(['solicitado_por'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cronograma_reajuste_solicitacao_id'), 'cronograma_reajuste_solicitacao', ['id'], unique=False)
    op.create_index(op.f('ix_cronograma_reajuste_solicitacao_projeto_escopo_id'), 'cronograma_reajuste_solicitacao', ['projeto_escopo_id'], unique=False)
    op.alter_column('notificacao', 'tipo',
               existing_type=mysql.ENUM('alocado_em_projeto', 'entrega_registrada', 'banca_remarcada', 'entrega_alterada', 'escalacao_banca', 'troca_banca', 'avaliacao_pendente', 'banca_aviso', 'lote_desempenho_aberto', 'pdi_prazo_proximo', 'pdi_prazo_vencido', 'kickoff_pendente', 'tarefa_vencida', 'banca_nao_marcada', 'projeto_sem_reuniao', 'banca_hoje'),
               type_=sa.Enum('alocado_em_projeto', 'entrega_registrada', 'banca_remarcada', 'entrega_alterada', 'escalacao_banca', 'troca_banca', 'avaliacao_pendente', 'banca_aviso', 'lote_desempenho_aberto', 'pdi_prazo_proximo', 'pdi_prazo_vencido', 'reajuste_solicitado', 'reajuste_respondido', 'kickoff_pendente', 'tarefa_vencida', 'banca_nao_marcada', 'projeto_sem_reuniao', 'banca_hoje', name='tipo_notificacao'),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('notificacao', 'tipo',
               existing_type=sa.Enum('alocado_em_projeto', 'entrega_registrada', 'banca_remarcada', 'entrega_alterada', 'escalacao_banca', 'troca_banca', 'avaliacao_pendente', 'banca_aviso', 'lote_desempenho_aberto', 'pdi_prazo_proximo', 'pdi_prazo_vencido', 'reajuste_solicitado', 'reajuste_respondido', 'kickoff_pendente', 'tarefa_vencida', 'banca_nao_marcada', 'projeto_sem_reuniao', 'banca_hoje', name='tipo_notificacao'),
               type_=mysql.ENUM('alocado_em_projeto', 'entrega_registrada', 'banca_remarcada', 'entrega_alterada', 'escalacao_banca', 'troca_banca', 'avaliacao_pendente', 'banca_aviso', 'lote_desempenho_aberto', 'pdi_prazo_proximo', 'pdi_prazo_vencido', 'kickoff_pendente', 'tarefa_vencida', 'banca_nao_marcada', 'projeto_sem_reuniao', 'banca_hoje'),
               existing_nullable=False)
    op.drop_index(op.f('ix_cronograma_reajuste_solicitacao_projeto_escopo_id'), table_name='cronograma_reajuste_solicitacao')
    op.drop_index(op.f('ix_cronograma_reajuste_solicitacao_id'), table_name='cronograma_reajuste_solicitacao')
    op.drop_table('cronograma_reajuste_solicitacao')
    # ### end Alembic commands ###
