"""add_tipo_justificativa_atraso

Revision ID: 9a51233fa680
Revises: aef487ec952b
Create Date: 2026-08-06 17:49:25.283221

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a51233fa680'
down_revision: Union[str, Sequence[str], None] = 'aef487ec952b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projeto_justificativa_atraso', sa.Column('tipo', sa.String(length=30), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projeto_justificativa_atraso', 'tipo')
    # ### end Alembic commands ###
