"""add_configuracao

Revision ID: a4f99ec3dfcb
Revises: e20e71f093b8
Create Date: 2026-07-28 20:47:40.786074

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a4f99ec3dfcb'
down_revision: Union[str, Sequence[str], None] = 'e20e71f093b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('configuracao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vagas_por_banca', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_configuracao_id'), 'configuracao', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_configuracao_id'), table_name='configuracao')
    op.drop_table('configuracao')
    # ### end Alembic commands ###
