"""add_token_recuperacao_senha

Revision ID: a9267ae28eeb
Revises: 5174eecb3b89
Create Date: 2026-08-05 16:27:04.695240

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a9267ae28eeb'
down_revision: Union[str, Sequence[str], None] = '5174eecb3b89'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('token_recuperacao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expira_em', sa.DateTime(), nullable=False),
    sa.Column('usado_em', sa.DateTime(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_token_recuperacao_id'), 'token_recuperacao', ['id'], unique=False)
    op.create_index(op.f('ix_token_recuperacao_token_hash'), 'token_recuperacao', ['token_hash'], unique=True)
    op.create_index(op.f('ix_token_recuperacao_usuario_id'), 'token_recuperacao', ['usuario_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_token_recuperacao_usuario_id'), table_name='token_recuperacao')
    op.drop_index(op.f('ix_token_recuperacao_token_hash'), table_name='token_recuperacao')
    op.drop_index(op.f('ix_token_recuperacao_id'), table_name='token_recuperacao')
    op.drop_table('token_recuperacao')
    # ### end Alembic commands ###
