"""projeto_remarcacao_banca

Revision ID: aef487ec952b
Revises: 9206e864f0b2
Create Date: 2026-08-06 17:30:33.375763

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aef487ec952b'
down_revision: Union[str, Sequence[str], None] = '9206e864f0b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projeto_remarcacao_banca',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('projeto_id', sa.Integer(), nullable=False),
    sa.Column('banca_id', sa.Integer(), nullable=False),
    sa.Column('projeto_escopo_id', sa.Integer(), nullable=True),
    sa.Column('data_anterior', sa.DateTime(), nullable=False),
    sa.Column('data_nova', sa.DateTime(), nullable=False),
    sa.Column('justificativa', sa.Text(), nullable=False),
    sa.Column('registrado_por', sa.Integer(), nullable=False),
    sa.Column('registrado_em', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['banca_id'], ['banca.id'], ),
    sa.ForeignKeyConstraint(['projeto_escopo_id'], ['projeto_escopo.id'], ),
    sa.ForeignKeyConstraint(['projeto_id'], ['projeto.id'], ),
    sa.ForeignKeyConstraint(['registrado_por'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projeto_remarcacao_banca_id'), 'projeto_remarcacao_banca', ['id'], unique=False)
    op.create_index(op.f('ix_projeto_remarcacao_banca_projeto_id'), 'projeto_remarcacao_banca', ['projeto_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_projeto_remarcacao_banca_projeto_id'), table_name='projeto_remarcacao_banca')
    op.drop_index(op.f('ix_projeto_remarcacao_banca_id'), table_name='projeto_remarcacao_banca')
    op.drop_table('projeto_remarcacao_banca')
    # ### end Alembic commands ###
