"""grade_horaria

Revision ID: af99d9ec2483
Revises: addea83280e5
Create Date: 2026-08-06 21:39:40.403529

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af99d9ec2483'
down_revision: Union[str, Sequence[str], None] = 'addea83280e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('grade_horaria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('semestre_id', sa.Integer(), nullable=False),
    sa.Column('dia_semana', sa.Integer(), nullable=False),
    sa.Column('hora_inicio', sa.Time(), nullable=False),
    sa.Column('hora_fim', sa.Time(), nullable=False),
    sa.ForeignKeyConstraint(['semestre_id'], ['semestre.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usuario_id', 'semestre_id', 'dia_semana', 'hora_inicio', name='uq_grade_horaria_usuario_semestre_dia_inicio')
    )
    op.create_index(op.f('ix_grade_horaria_id'), 'grade_horaria', ['id'], unique=False)
    op.create_index(op.f('ix_grade_horaria_semestre_id'), 'grade_horaria', ['semestre_id'], unique=False)
    op.create_index(op.f('ix_grade_horaria_usuario_id'), 'grade_horaria', ['usuario_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_grade_horaria_usuario_id'), table_name='grade_horaria')
    op.drop_index(op.f('ix_grade_horaria_semestre_id'), table_name='grade_horaria')
    op.drop_index(op.f('ix_grade_horaria_id'), table_name='grade_horaria')
    op.drop_table('grade_horaria')
    # ### end Alembic commands ###
