"""add_criado_em_projeto

Revision ID: b11cb0d16715
Revises: 1d4a1b5924d7
Create Date: 2026-08-04 17:16:18.727815

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b11cb0d16715'
down_revision: Union[str, Sequence[str], None] = '1d4a1b5924d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projeto', sa.Column('criado_em', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projeto', 'criado_em')
    # ### end Alembic commands ###
