"""remove_categoria_banca_e_cascade_delete_banca

Revision ID: b210b2233a5c
Revises: 1601abd6a525
Create Date: 2026-07-28 17:26:49.815254

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'b210b2233a5c'
down_revision: Union[str, Sequence[str], None] = '1601abd6a525'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Os nomes `*_ibfk_N` são a convenção do MySQL — no Postgres a FK sem nome
    # explícito nasce com outro padrão, então o hardcoded quebra lá. Busca o
    # nome de verdade pela coluna, mesmo truque do `9a017078a712`.
    conexao = op.get_bind()
    inspector = sa.inspect(conexao)

    def fk_por_coluna(tabela, coluna):
        for fk in inspector.get_foreign_keys(tabela):
            if fk['constrained_columns'] == [coluna]:
                return fk['name']
        raise RuntimeError(f"FK não encontrada em {tabela}.{coluna}")

    op.drop_constraint(fk_por_coluna('avaliacao', 'banca_id'), 'avaliacao', type_='foreignkey')
    op.create_foreign_key(None, 'avaliacao', 'banca', ['banca_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(fk_por_coluna('avaliacao_nota', 'avaliacao_id'), 'avaliacao_nota', type_='foreignkey')
    op.create_foreign_key(None, 'avaliacao_nota', 'avaliacao', ['avaliacao_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(fk_por_coluna('banca_frente', 'banca_id'), 'banca_frente', type_='foreignkey')
    op.create_foreign_key(None, 'banca_frente', 'banca', ['banca_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(fk_por_coluna('candidatura', 'banca_id'), 'candidatura', type_='foreignkey')
    op.create_foreign_key(None, 'candidatura', 'banca', ['banca_id'], ['id'], ondelete='CASCADE')
    op.drop_column('cargo', 'categoria_banca')
    op.drop_constraint(fk_por_coluna('equipe_projeto', 'banca_id'), 'equipe_projeto', type_='foreignkey')
    op.create_foreign_key(None, 'equipe_projeto', 'banca', ['banca_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'equipe_projeto', type_='foreignkey')
    op.create_foreign_key(op.f('equipe_projeto_ibfk_1'), 'equipe_projeto', 'banca', ['banca_id'], ['id'])
    op.add_column('cargo', sa.Column('categoria_banca', mysql.VARCHAR(length=50), nullable=False))
    op.drop_constraint(None, 'candidatura', type_='foreignkey')
    op.create_foreign_key(op.f('candidatura_ibfk_1'), 'candidatura', 'banca', ['banca_id'], ['id'])
    op.drop_constraint(None, 'banca_frente', type_='foreignkey')
    op.create_foreign_key(op.f('banca_frente_ibfk_1'), 'banca_frente', 'banca', ['banca_id'], ['id'])
    op.drop_constraint(None, 'avaliacao_nota', type_='foreignkey')
    op.create_foreign_key(op.f('avaliacao_nota_ibfk_1'), 'avaliacao_nota', 'avaliacao', ['avaliacao_id'], ['id'])
    op.drop_constraint(None, 'avaliacao', type_='foreignkey')
    op.create_foreign_key(op.f('avaliacao_ibfk_2'), 'avaliacao', 'banca', ['banca_id'], ['id'])
    # ### end Alembic commands ###
