"""add_desempenho_periodico

Revision ID: b750178a39d0
Revises: 17d30a742ef6
Create Date: 2026-08-04 20:30:55.786820

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b750178a39d0'
down_revision: Union[str, Sequence[str], None] = '17d30a742ef6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('desempenho_formulario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.Enum('periodico', 'finalizacao', name='desempenho_formulario_tipo'), nullable=False),
    sa.Column('papel', sa.Enum('consultor', 'coordenador', name='desempenho_formulario_papel'), nullable=False),
    sa.Column('nota_geral_titulo', sa.String(length=200), nullable=False),
    sa.Column('nota_geral_descricao', sa.Text(), nullable=False),
    sa.Column('comentarios_titulo', sa.String(length=200), nullable=False),
    sa.Column('comentarios_descricao', sa.Text(), nullable=False),
    sa.Column('comentarios_aviso', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tipo', 'papel', name='uq_desempenho_formulario_tipo_papel')
    )
    op.create_index(op.f('ix_desempenho_formulario_id'), 'desempenho_formulario', ['id'], unique=False)
    op.create_table('desempenho_lote',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('tipo', sa.Enum('periodico', 'finalizacao', name='desempenho_lote_tipo'), nullable=False),
    sa.Column('data_inicio', sa.DateTime(), nullable=False),
    sa.Column('data_fim', sa.DateTime(), nullable=False),
    sa.Column('override_manual', sa.Enum('aberto', 'fechado', name='desempenho_lote_override'), nullable=True),
    sa.Column('criado_em', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_desempenho_lote_id'), 'desempenho_lote', ['id'], unique=False)
    op.create_table('desempenho_formulario_secao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('formulario_id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('ordem', sa.Integer(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['formulario_id'], ['desempenho_formulario.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_desempenho_formulario_secao_formulario_id'), 'desempenho_formulario_secao', ['formulario_id'], unique=False)
    op.create_index(op.f('ix_desempenho_formulario_secao_id'), 'desempenho_formulario_secao', ['id'], unique=False)
    op.create_table('desempenho_avaliacao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lote_id', sa.Integer(), nullable=False),
    sa.Column('formulario_id', sa.Integer(), nullable=False),
    sa.Column('avaliador_id', sa.Integer(), nullable=False),
    sa.Column('avaliado_id', sa.Integer(), nullable=False),
    sa.Column('nota_geral', sa.Integer(), nullable=False),
    sa.Column('comentarios', sa.Text(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['avaliado_id'], ['usuario.id'], ),
    sa.ForeignKeyConstraint(['avaliador_id'], ['usuario.id'], ),
    sa.ForeignKeyConstraint(['formulario_id'], ['desempenho_formulario.id'], ),
    sa.ForeignKeyConstraint(['lote_id'], ['desempenho_lote.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lote_id', 'avaliador_id', 'avaliado_id', name='uq_desempenho_avaliacao_par')
    )
    op.create_index(op.f('ix_desempenho_avaliacao_avaliado_id'), 'desempenho_avaliacao', ['avaliado_id'], unique=False)
    op.create_index(op.f('ix_desempenho_avaliacao_avaliador_id'), 'desempenho_avaliacao', ['avaliador_id'], unique=False)
    op.create_index(op.f('ix_desempenho_avaliacao_id'), 'desempenho_avaliacao', ['id'], unique=False)
    op.create_index(op.f('ix_desempenho_avaliacao_lote_id'), 'desempenho_avaliacao', ['lote_id'], unique=False)
    op.create_table('desempenho_criterio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('secao_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('tipo_resposta', sa.Enum('nota', 'texto', name='desempenho_criterio_tipo_resposta'), server_default='nota', nullable=False),
    sa.Column('limite_caracteres', sa.Integer(), nullable=True),
    sa.Column('ordem', sa.Integer(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['secao_id'], ['desempenho_formulario_secao.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_desempenho_criterio_id'), 'desempenho_criterio', ['id'], unique=False)
    op.create_index(op.f('ix_desempenho_criterio_secao_id'), 'desempenho_criterio', ['secao_id'], unique=False)
    op.create_table('desempenho_lote_finalizado',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lote_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('finalizado_em', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['lote_id'], ['desempenho_lote.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lote_id', 'usuario_id', name='uq_desempenho_lote_finalizado')
    )
    op.create_index(op.f('ix_desempenho_lote_finalizado_id'), 'desempenho_lote_finalizado', ['id'], unique=False)
    op.create_index(op.f('ix_desempenho_lote_finalizado_lote_id'), 'desempenho_lote_finalizado', ['lote_id'], unique=False)
    op.create_index(op.f('ix_desempenho_lote_finalizado_usuario_id'), 'desempenho_lote_finalizado', ['usuario_id'], unique=False)
    op.create_table('desempenho_mentoria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mentor_id', sa.Integer(), nullable=False),
    sa.Column('mentorado_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['mentor_id'], ['usuario.id'], ),
    sa.ForeignKeyConstraint(['mentorado_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_desempenho_mentoria_id'), 'desempenho_mentoria', ['id'], unique=False)
    op.create_index(op.f('ix_desempenho_mentoria_mentor_id'), 'desempenho_mentoria', ['mentor_id'], unique=False)
    op.create_index(op.f('ix_desempenho_mentoria_mentorado_id'), 'desempenho_mentoria', ['mentorado_id'], unique=True)
    op.create_table('desempenho_avaliacao_nota',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('avaliacao_id', sa.Integer(), nullable=False),
    sa.Column('criterio_id', sa.Integer(), nullable=False),
    sa.Column('nota', sa.Integer(), nullable=True),
    sa.Column('resposta_texto', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['avaliacao_id'], ['desempenho_avaliacao.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['criterio_id'], ['desempenho_criterio.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_desempenho_avaliacao_nota_avaliacao_id'), 'desempenho_avaliacao_nota', ['avaliacao_id'], unique=False)
    op.create_index(op.f('ix_desempenho_avaliacao_nota_criterio_id'), 'desempenho_avaliacao_nota', ['criterio_id'], unique=False)
    op.create_index(op.f('ix_desempenho_avaliacao_nota_id'), 'desempenho_avaliacao_nota', ['id'], unique=False)
    op.create_table('desempenho_lote_projeto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lote_id', sa.Integer(), nullable=False),
    sa.Column('projeto_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['lote_id'], ['desempenho_lote.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['projeto_id'], ['projeto.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lote_id', 'projeto_id', name='uq_desempenho_lote_projeto')
    )
    op.create_index(op.f('ix_desempenho_lote_projeto_id'), 'desempenho_lote_projeto', ['id'], unique=False)
    op.create_index(op.f('ix_desempenho_lote_projeto_lote_id'), 'desempenho_lote_projeto', ['lote_id'], unique=False)
    op.create_index(op.f('ix_desempenho_lote_projeto_projeto_id'), 'desempenho_lote_projeto', ['projeto_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ⚠ Correção manual: o autogenerate propunha `DROP INDEX` explícito antes
    # de cada `DROP TABLE`, mas no MySQL isso falha quando o índice sustenta
    # uma FK (ex.: ix_desempenho_lote_projeto_projeto_id). `DROP TABLE` já
    # remove índices e FKs da própria tabela sozinho — só a ordem entre
    # tabelas (filha antes da pai) importa aqui.
    op.drop_table('desempenho_lote_projeto')
    op.drop_table('desempenho_avaliacao_nota')
    op.drop_table('desempenho_mentoria')
    op.drop_table('desempenho_lote_finalizado')
    op.drop_table('desempenho_criterio')
    op.drop_table('desempenho_avaliacao')
    op.drop_table('desempenho_formulario_secao')
    op.drop_table('desempenho_lote')
    op.drop_table('desempenho_formulario')
