"""F3 projeto: projeto, projeto_frente, projeto_membro, projeto_status_historico

Revision ID: bea367c8fc83
Revises: 8b6e0c9ca6d9
Create Date: 2026-08-04 10:44:05.369175

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bea367c8fc83'
down_revision: Union[str, Sequence[str], None] = '8b6e0c9ca6d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projeto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('cliente', sa.String(length=150), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('link_proposta', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('vendido', 'ambientacao', 'em_andamento', 'validacao_bancas', 'envio_tep', 'periodo_ajustes', 'finalizado', 'pausado', name='status_projeto'), server_default='vendido', nullable=False),
    sa.Column('dias_ambientacao', sa.Integer(), server_default='5', nullable=False),
    sa.Column('data_kickoff', sa.Date(), nullable=True),
    sa.Column('data_entrega_cliente', sa.Date(), nullable=True),
    sa.Column('dia_reuniao_padrao', sa.Integer(), nullable=True),
    sa.Column('criado_por', sa.Integer(), nullable=False),
    sa.Column('status_antes_pausa', sa.String(length=30), nullable=True),
    sa.ForeignKeyConstraint(['criado_por'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projeto_id'), 'projeto', ['id'], unique=False)
    op.create_table('projeto_frente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('projeto_id', sa.Integer(), nullable=False),
    sa.Column('frente_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['frente_id'], ['frente.id'], ),
    sa.ForeignKeyConstraint(['projeto_id'], ['projeto.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('projeto_id', 'frente_id', name='uq_projeto_frente')
    )
    op.create_index(op.f('ix_projeto_frente_frente_id'), 'projeto_frente', ['frente_id'], unique=False)
    op.create_index(op.f('ix_projeto_frente_id'), 'projeto_frente', ['id'], unique=False)
    op.create_index(op.f('ix_projeto_frente_projeto_id'), 'projeto_frente', ['projeto_id'], unique=False)
    op.create_table('projeto_membro',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('projeto_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('papel', sa.Enum('coordenador', 'consultor', name='papel_projeto_membro'), nullable=False),
    sa.Column('entrou_em', sa.Date(), nullable=False),
    sa.Column('saiu_em', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['projeto_id'], ['projeto.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projeto_membro_id'), 'projeto_membro', ['id'], unique=False)
    op.create_index(op.f('ix_projeto_membro_projeto_id'), 'projeto_membro', ['projeto_id'], unique=False)
    op.create_index(op.f('ix_projeto_membro_usuario_id'), 'projeto_membro', ['usuario_id'], unique=False)
    op.create_table('projeto_status_historico',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('projeto_id', sa.Integer(), nullable=False),
    sa.Column('status_anterior', sa.Enum('vendido', 'ambientacao', 'em_andamento', 'validacao_bancas', 'envio_tep', 'periodo_ajustes', 'finalizado', 'pausado', name='status_historico_projeto'), nullable=True),
    sa.Column('status_novo', sa.Enum('vendido', 'ambientacao', 'em_andamento', 'validacao_bancas', 'envio_tep', 'periodo_ajustes', 'finalizado', 'pausado', name='status_historico_projeto'), nullable=False),
    sa.Column('alterado_por', sa.Integer(), nullable=True),
    sa.Column('alterado_em', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['alterado_por'], ['usuario.id'], ),
    sa.ForeignKeyConstraint(['projeto_id'], ['projeto.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projeto_status_historico_id'), 'projeto_status_historico', ['id'], unique=False)
    op.create_index(op.f('ix_projeto_status_historico_projeto_id'), 'projeto_status_historico', ['projeto_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_projeto_status_historico_projeto_id'), table_name='projeto_status_historico')
    op.drop_index(op.f('ix_projeto_status_historico_id'), table_name='projeto_status_historico')
    op.drop_table('projeto_status_historico')
    op.drop_index(op.f('ix_projeto_membro_usuario_id'), table_name='projeto_membro')
    op.drop_index(op.f('ix_projeto_membro_projeto_id'), table_name='projeto_membro')
    op.drop_index(op.f('ix_projeto_membro_id'), table_name='projeto_membro')
    op.drop_table('projeto_membro')
    op.drop_index(op.f('ix_projeto_frente_projeto_id'), table_name='projeto_frente')
    op.drop_index(op.f('ix_projeto_frente_id'), table_name='projeto_frente')
    op.drop_index(op.f('ix_projeto_frente_frente_id'), table_name='projeto_frente')
    op.drop_table('projeto_frente')
    op.drop_index(op.f('ix_projeto_id'), table_name='projeto')
    op.drop_table('projeto')
    # ### end Alembic commands ###
