"""f7_f8_tarefa_reuniao_semanal

Revision ID: d0b3af873672
Revises: 0b57c2b6b9aa
Create Date: 2026-08-04 14:56:41.571270

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0b3af873672'
down_revision: Union[str, Sequence[str], None] = '0b57c2b6b9aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reuniao_semanal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('projeto_id', sa.Integer(), nullable=False),
    sa.Column('data_reuniao', sa.Date(), nullable=False),
    sa.Column('registrado_por', sa.Integer(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['projeto_id'], ['projeto.id'], ),
    sa.ForeignKeyConstraint(['registrado_por'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('projeto_id', 'data_reuniao', name='uq_reuniao_projeto_data')
    )
    op.create_index(op.f('ix_reuniao_semanal_data_reuniao'), 'reuniao_semanal', ['data_reuniao'], unique=False)
    op.create_index(op.f('ix_reuniao_semanal_id'), 'reuniao_semanal', ['id'], unique=False)
    op.create_index(op.f('ix_reuniao_semanal_projeto_id'), 'reuniao_semanal', ['projeto_id'], unique=False)
    op.create_table('tarefa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('projeto_id', sa.Integer(), nullable=False),
    sa.Column('projeto_escopo_id', sa.Integer(), nullable=True),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('responsavel_id', sa.Integer(), nullable=False),
    sa.Column('prazo', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('a_fazer', 'em_andamento', 'validacao', 'concluido', 'cancelado', name='status_tarefa'), server_default='a_fazer', nullable=False),
    sa.Column('criado_por', sa.Integer(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('movida_em', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['criado_por'], ['usuario.id'], ),
    sa.ForeignKeyConstraint(['projeto_escopo_id'], ['projeto_escopo.id'], ),
    sa.ForeignKeyConstraint(['projeto_id'], ['projeto.id'], ),
    sa.ForeignKeyConstraint(['responsavel_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tarefa_id'), 'tarefa', ['id'], unique=False)
    op.create_index(op.f('ix_tarefa_projeto_escopo_id'), 'tarefa', ['projeto_escopo_id'], unique=False)
    op.create_index(op.f('ix_tarefa_projeto_id'), 'tarefa', ['projeto_id'], unique=False)
    op.create_index(op.f('ix_tarefa_responsavel_id'), 'tarefa', ['responsavel_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tarefa_responsavel_id'), table_name='tarefa')
    op.drop_index(op.f('ix_tarefa_projeto_id'), table_name='tarefa')
    op.drop_index(op.f('ix_tarefa_projeto_escopo_id'), table_name='tarefa')
    op.drop_index(op.f('ix_tarefa_id'), table_name='tarefa')
    op.drop_table('tarefa')
    op.drop_index(op.f('ix_reuniao_semanal_projeto_id'), table_name='reuniao_semanal')
    op.drop_index(op.f('ix_reuniao_semanal_id'), table_name='reuniao_semanal')
    op.drop_index(op.f('ix_reuniao_semanal_data_reuniao'), table_name='reuniao_semanal')
    op.drop_table('reuniao_semanal')
    # ### end Alembic commands ###
