"""tipo_notificacao_solicitacao_projeto

Revision ID: d66e88dfc475
Revises: 00b38e9fa008
Create Date: 2026-08-07 04:35:39.198730

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'd66e88dfc475'
down_revision: Union[str, Sequence[str], None] = '00b38e9fa008'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('notificacao', 'tipo',
               existing_type=mysql.ENUM('alocado_em_projeto', 'entrega_registrada', 'banca_remarcada', 'entrega_alterada', 'escalacao_banca', 'troca_banca', 'avaliacao_pendente', 'banca_aviso', 'lote_desempenho_aberto', 'pdi_prazo_proximo', 'pdi_prazo_vencido', 'kickoff_pendente', 'tarefa_vencida', 'banca_nao_marcada', 'projeto_sem_reuniao', 'banca_hoje', 'reajuste_solicitado', 'reajuste_respondido', collation='utf8mb4_unicode_ci'),
               type_=sa.Enum('alocado_em_projeto', 'solicitacao_projeto', 'entrega_registrada', 'banca_remarcada', 'entrega_alterada', 'escalacao_banca', 'troca_banca', 'avaliacao_pendente', 'banca_aviso', 'lote_desempenho_aberto', 'pdi_prazo_proximo', 'pdi_prazo_vencido', 'kickoff_pendente', 'tarefa_vencida', 'reajuste_solicitado', 'reajuste_respondido', 'banca_nao_marcada', 'projeto_sem_reuniao', 'banca_hoje', name='tipo_notificacao'),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('notificacao', 'tipo',
               existing_type=sa.Enum('alocado_em_projeto', 'solicitacao_projeto', 'entrega_registrada', 'banca_remarcada', 'entrega_alterada', 'escalacao_banca', 'troca_banca', 'avaliacao_pendente', 'banca_aviso', 'lote_desempenho_aberto', 'pdi_prazo_proximo', 'pdi_prazo_vencido', 'kickoff_pendente', 'tarefa_vencida', 'reajuste_solicitado', 'reajuste_respondido', 'banca_nao_marcada', 'projeto_sem_reuniao', 'banca_hoje', name='tipo_notificacao'),
               type_=mysql.ENUM('alocado_em_projeto', 'entrega_registrada', 'banca_remarcada', 'entrega_alterada', 'escalacao_banca', 'troca_banca', 'avaliacao_pendente', 'banca_aviso', 'lote_desempenho_aberto', 'pdi_prazo_proximo', 'pdi_prazo_vencido', 'kickoff_pendente', 'tarefa_vencida', 'banca_nao_marcada', 'projeto_sem_reuniao', 'banca_hoje', 'reajuste_solicitado', 'reajuste_respondido', collation='utf8mb4_unicode_ci'),
               existing_nullable=False)
    # ### end Alembic commands ###
