"""create_initial_tables

Revision ID: dbdc7370bada
Revises: 
Create Date: 2026-07-24 01:45:56.188461

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dbdc7370bada'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cargo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('categoria_banca', sa.String(length=50), nullable=False),
    sa.Column('pode_definir_formulario', sa.Boolean(), nullable=False),
    sa.Column('pode_agendar_banca', sa.Boolean(), nullable=False),
    sa.Column('pode_gerenciar_cargos', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cargo_id'), 'cargo', ['id'], unique=False)
    op.create_table('escopo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_escopo_id'), 'escopo', ['id'], unique=False)
    op.create_table('semestre',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=20), nullable=False),
    sa.Column('inicio', sa.Date(), nullable=False),
    sa.Column('fim', sa.Date(), nullable=False),
    sa.Column('nota_corte', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('vagas_nucleo', sa.Integer(), nullable=False),
    sa.Column('vagas_lideranca', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_semestre_id'), 'semestre', ['id'], unique=False)
    op.create_table('formulario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('semestre_id', sa.Integer(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['semestre_id'], ['semestre.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_formulario_id'), 'formulario', ['id'], unique=False)
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('email_insper', sa.String(length=150), nullable=False),
    sa.Column('cargo_id', sa.Integer(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['cargo_id'], ['cargo.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email_insper')
    )
    op.create_index(op.f('ix_usuario_id'), 'usuario', ['id'], unique=False)
    op.create_table('banca',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome_projeto', sa.String(length=150), nullable=False),
    sa.Column('escopo_id', sa.Integer(), nullable=False),
    sa.Column('coordenador_id', sa.Integer(), nullable=False),
    sa.Column('data_hora', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('nota_final', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['coordenador_id'], ['usuario.id'], ),
    sa.ForeignKeyConstraint(['escopo_id'], ['escopo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_banca_id'), 'banca', ['id'], unique=False)
    op.create_table('pergunta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('formulario_id', sa.Integer(), nullable=False),
    sa.Column('texto', sa.String(length=500), nullable=False),
    sa.Column('ordem', sa.Integer(), nullable=False),
    sa.Column('tipo_resposta', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['formulario_id'], ['formulario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pergunta_id'), 'pergunta', ['id'], unique=False)
    op.create_table('avaliacao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('banca_id', sa.Integer(), nullable=False),
    sa.Column('avaliador_id', sa.Integer(), nullable=False),
    sa.Column('formulario_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('comentario_feedback', sa.String(length=1000), nullable=True),
    sa.Column('submetida_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['avaliador_id'], ['usuario.id'], ),
    sa.ForeignKeyConstraint(['banca_id'], ['banca.id'], ),
    sa.ForeignKeyConstraint(['formulario_id'], ['formulario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_avaliacao_id'), 'avaliacao', ['id'], unique=False)
    op.create_table('candidatura',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('banca_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('categoria', sa.String(length=50), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('confirmado', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['banca_id'], ['banca.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_candidatura_id'), 'candidatura', ['id'], unique=False)
    op.create_table('avaliacao_nota',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('avaliacao_id', sa.Integer(), nullable=False),
    sa.Column('pergunta_id', sa.Integer(), nullable=False),
    sa.Column('nota', sa.Numeric(precision=2, scale=1), nullable=True),
    sa.Column('resposta_texto', sa.String(length=1000), nullable=True),
    sa.ForeignKeyConstraint(['avaliacao_id'], ['avaliacao.id'], ),
    sa.ForeignKeyConstraint(['pergunta_id'], ['pergunta.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_avaliacao_nota_id'), 'avaliacao_nota', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_avaliacao_nota_id'), table_name='avaliacao_nota')
    op.drop_table('avaliacao_nota')
    op.drop_index(op.f('ix_candidatura_id'), table_name='candidatura')
    op.drop_table('candidatura')
    op.drop_index(op.f('ix_avaliacao_id'), table_name='avaliacao')
    op.drop_table('avaliacao')
    op.drop_index(op.f('ix_pergunta_id'), table_name='pergunta')
    op.drop_table('pergunta')
    op.drop_index(op.f('ix_banca_id'), table_name='banca')
    op.drop_table('banca')
    op.drop_index(op.f('ix_usuario_id'), table_name='usuario')
    op.drop_table('usuario')
    op.drop_index(op.f('ix_formulario_id'), table_name='formulario')
    op.drop_table('formulario')
    op.drop_index(op.f('ix_semestre_id'), table_name='semestre')
    op.drop_table('semestre')
    op.drop_index(op.f('ix_escopo_id'), table_name='escopo')
    op.drop_table('escopo')
    op.drop_index(op.f('ix_cargo_id'), table_name='cargo')
    op.drop_table('cargo')
    # ### end Alembic commands ###
