"""f4_projeto_escopo

Revision ID: dc5bc4321c2c
Revises: bea367c8fc83
Create Date: 2026-08-04 14:12:20.875808

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc5bc4321c2c'
down_revision: Union[str, Sequence[str], None] = 'bea367c8fc83'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projeto_escopo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('projeto_id', sa.Integer(), nullable=False),
    sa.Column('escopo_id', sa.Integer(), nullable=True),
    sa.Column('nome_customizado', sa.String(length=150), nullable=True),
    sa.Column('frente_id', sa.Integer(), nullable=False),
    sa.Column('dias_uteis_vendidos', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('nao_iniciado', 'em_andamento', 'entregue', 'cancelado', name='status_projeto_escopo'), server_default='nao_iniciado', nullable=False),
    sa.Column('data_inicio', sa.Date(), nullable=True),
    sa.Column('cronograma_oficializado_em', sa.DateTime(), nullable=True),
    sa.Column('data_entrega_planejada', sa.Date(), nullable=True),
    sa.Column('data_entrega_real', sa.Date(), nullable=True),
    sa.Column('tipo_atraso_entrega', sa.Enum('interno', 'externo', name='tipo_atraso_entrega_escopo'), nullable=True),
    sa.ForeignKeyConstraint(['escopo_id'], ['escopo.id'], ),
    sa.ForeignKeyConstraint(['frente_id'], ['frente.id'], ),
    sa.ForeignKeyConstraint(['projeto_id'], ['projeto.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projeto_escopo_escopo_id'), 'projeto_escopo', ['escopo_id'], unique=False)
    op.create_index(op.f('ix_projeto_escopo_frente_id'), 'projeto_escopo', ['frente_id'], unique=False)
    op.create_index(op.f('ix_projeto_escopo_id'), 'projeto_escopo', ['id'], unique=False)
    op.create_index(op.f('ix_projeto_escopo_projeto_id'), 'projeto_escopo', ['projeto_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_projeto_escopo_projeto_id'), table_name='projeto_escopo')
    op.drop_index(op.f('ix_projeto_escopo_id'), table_name='projeto_escopo')
    op.drop_index(op.f('ix_projeto_escopo_frente_id'), table_name='projeto_escopo')
    op.drop_index(op.f('ix_projeto_escopo_escopo_id'), table_name='projeto_escopo')
    op.drop_table('projeto_escopo')
    # ### end Alembic commands ###
