"""usuario_criado_por_nullable_para_exclusao_permanente

Revision ID: deda213224f9
Revises: c3993055bd44
Create Date: 2026-08-07 02:29:32.531029

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'deda213224f9'
down_revision: Union[str, Sequence[str], None] = 'c3993055bd44'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('projeto', 'criado_por',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('reuniao_semanal', 'registrado_por',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('tarefa', 'criado_por',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
    # Nota: o autogenerate também detectou uma renomeação de índice em
    # `tarefa_coluna` (ix_tarefa_coluna_pk_id -> ix_tarefa_coluna_id) sem
    # relação nenhuma com esta migration — ruído de uma correção antiga de
    # portabilidade MySQL->Postgres, removido daqui de propósito.


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tarefa', 'criado_por',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('reuniao_semanal', 'registrado_por',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('projeto', 'criado_por',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
