"""remove_categoria_de_candidatura

Revision ID: e20e71f093b8
Revises: 1f5ee66b79a2
Create Date: 2026-07-28 20:12:52.532225

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'e20e71f093b8'
down_revision: Union[str, Sequence[str], None] = '1f5ee66b79a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('candidatura', 'categoria')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidatura', sa.Column('categoria', mysql.VARCHAR(length=50), nullable=False))
    # ### end Alembic commands ###
