"""

Revision ID: ef365a1cc656
Revises: d3a7b91c5e04
Create Date: 2026-08-07 04:32:12.925409

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef365a1cc656'
down_revision: Union[str, Sequence[str], None] = 'd3a7b91c5e04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tarefa_coluna_id_fk'), table_name='tarefa')
    op.create_index(op.f('ix_tarefa_coluna_id'), 'tarefa', ['coluna_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tarefa_coluna_id'), table_name='tarefa')
    op.create_index(op.f('ix_tarefa_coluna_id_fk'), 'tarefa', ['coluna_id'], unique=False)
    # ### end Alembic commands ###
