"""add_arquivado_em_projeto

Revision ID: fb72df6402d6
Revises: b11cb0d16715
Create Date: 2026-08-04 17:36:37.205899

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb72df6402d6'
down_revision: Union[str, Sequence[str], None] = 'b11cb0d16715'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projeto', sa.Column('arquivado_em', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projeto', 'arquivado_em')
    # ### end Alembic commands ###
