"""pergunta_escopo_e_catalogo_avaliacao

Revision ID: ff536b09e0a2
Revises: 0cd1a5deb16f
Create Date: 2026-08-05 11:01:34.459805

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff536b09e0a2'
down_revision: Union[str, Sequence[str], None] = '0cd1a5deb16f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# Uma pergunta por bloco técnico do formulário de avaliação de bancas, uma
# lista por escopo — pergunta.escopo_id aponta pra cá. Espelhado em
# scripts/seed.py para quem sobe um banco novo do zero.
BLOCOS_TECNICOS: dict[str, list[str]] = {
    "Análise Mercadológica": [
        "Storytelling",
        "Solução Consistente",
        "Embasamento de Hipóteses/Soluções",
        "Clareza de Recomendações/Insights",
    ],
    "Plano Operacional": [
        "Storytelling",
        "Plano de Ação",
        "Uso de Ferramentas",
        "Tangibilidade das Recomendações",
    ],
    "Plano Estratégico de Marketing": [
        "Storytelling",
        "Plano de Ação",
        "Uso de Ferramentas",
        "Tangibilidade das Recomendações",
    ],
    "Plano Financeiro": [
        "Premissas Utilizadas",
        "Organização do Excel",
        "Apresentação de Resultados",
    ],
    "Análise de Dados": [
        "Qualidade do Código",
        "Relevância dos Dados",
        "Clareza dos Resultados",
    ],
    "Desenvolvimento Web (Mock-Up)": [
        "Experiência de Uso",
        "Coerência com Público-Alvo",
        "Organização da Figma",
    ],
    "Desenvolvimento Web (Front/Back)": [
        "Organização do Código",
        "Coerência com Figma",
        "Usabilidade e UX",
    ],
    "Planejamento Consultivo Tributário": [
        "Aderência na Simulação",
        "Organização do Excel",
        "Clareza e Recomendações/Insights",
        "Estrutura do Parecer",
    ],
    "Planejamento Consultivo Societário": [
        "Solução Coerente para o Cliente",
        "Enquadramento Correto",
        "Mapeamento dos Documentos/Processos Corretos",
        "Estrutura do Parecer",
    ],
    "Planejamento Consultivo de Propriedade Industrial": [
        "Pesquisa INPI Completa",
        "Estrutura do Parecer",
        "Sugestão Coerente para o Cliente",
    ],
    "Elaboração Contratual": [
        "Segurança Jurídica/Equilíbrio Contratual",
        "Nível de Personalização",
        "Clareza (considerando organização e escrita)",
        "Previsibilidade Coerente (gestão de riscos)",
    ],
    "Revisão Contratual": [
        "Clareza (considerando organização e escrita)",
        "Comparação Clara entre Cláusula Antiga e Nova",
        "Justificativas para Alteração Coerente",
    ],
    # Simulação e Otimização de Processos entra no catálogo mas nasce sem
    # pergunta própria — a diretoria cadastra as dela pelo editor.
}

BLOCO_FINAL_UNIVERSAL = ["Design Visual", "Clareza de Texto", "Visuais Completos"]

RENOMEIOS_ESCOPO = {
    "Viabilidade Financeira": "Plano Financeiro",
    "Planejamento e Análise Tributária": "Planejamento Consultivo Tributário",
    "Elaboração e/ou Revisão Contratual": "Elaboração Contratual",
}

NOVOS_ESCOPOS = [
    ("Revisão Contratual", "Direito"),
    ("Análise de Dados", "Tech"),
    ("Desenvolvimento Web (Mock-Up)", "Tech"),
    ("Desenvolvimento Web (Front/Back)", "Tech"),
]


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pergunta', sa.Column('escopo_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_pergunta_escopo_id'), 'pergunta', ['escopo_id'], unique=False)
    op.create_foreign_key(None, 'pergunta', 'escopo', ['escopo_id'], ['id'])
    # ### end Alembic commands ###

    _migrar_catalogo_e_perguntas()


def _migrar_catalogo_e_perguntas() -> None:
    """Alinha o catálogo de escopo com o nome usado no formulário de
    avaliação e semeia as perguntas de cada bloco técnico no formulário
    ativo. `escopo_id` nulo = pergunta universal (Bloco 3)."""
    conn = op.get_bind()

    for antigo, novo in RENOMEIOS_ESCOPO.items():
        conn.execute(
            sa.text("UPDATE escopo SET nome = :novo WHERE nome = :antigo"),
            {"novo": novo, "antigo": antigo},
        )

    for nome, nome_frente in NOVOS_ESCOPOS:
        ja_existe = conn.execute(
            sa.text("SELECT id FROM escopo WHERE nome = :nome"), {"nome": nome}
        ).scalar()
        if ja_existe:
            continue
        frente_id = conn.execute(
            sa.text("SELECT id FROM frente WHERE nome = :nome"), {"nome": nome_frente}
        ).scalar()
        conn.execute(
            sa.text(
                "INSERT INTO escopo (nome, frente_id, ativo) VALUES (:nome, :frente_id, true)"
            ),
            {"nome": nome, "frente_id": frente_id},
        )

    formulario_id = conn.execute(
        sa.text("SELECT id FROM formulario WHERE ativo = true ORDER BY id DESC LIMIT 1")
    ).scalar()
    if not formulario_id:
        # Ninguém publicou uma versão do formulário ainda (ex.: banco de
        # desenvolvimento recém-migrado) — cria uma pra já nascer com as
        # perguntas dos blocos técnicos, em vez de deixar a avaliação sem
        # nenhum formulário ativo.
        # CURRENT_DATE é sinônimo de CURDATE() no MySQL — uma forma só que
        # roda nos dois.
        semestre_id = conn.execute(
            sa.text(
                "SELECT id FROM semestre WHERE CURRENT_DATE BETWEEN inicio AND fim "
                "ORDER BY inicio DESC LIMIT 1"
            )
        ).scalar()
        if not semestre_id:
            semestre_id = conn.execute(
                sa.text("SELECT id FROM semestre ORDER BY inicio DESC LIMIT 1")
            ).scalar()
        if not semestre_id:
            # Sem nenhum semestre cadastrado (banco vazio de verdade) — não
            # há como associar um formulário; scripts/seed.py cobre a carga
            # inicial completa nesse caso.
            return
        # `.lastrowid` é MySQL/SQLite — o Postgres não tem "last insert id"
        # de cursor, então busca de volta em vez de depender dele.
        conn.execute(
            sa.text(
                "INSERT INTO formulario (semestre_id, ativo) VALUES (:semestre_id, true)"
            ),
            {"semestre_id": semestre_id},
        )
        formulario_id = conn.execute(
            sa.text("SELECT id FROM formulario WHERE semestre_id = :semestre_id ORDER BY id DESC LIMIT 1"),
            {"semestre_id": semestre_id},
        ).scalar()

    ordem = (
        conn.execute(
            sa.text("SELECT COALESCE(MAX(ordem), 0) FROM pergunta WHERE formulario_id = :fid"),
            {"fid": formulario_id},
        ).scalar()
        or 0
    )

    def inserir_pergunta(texto: str, escopo_id):
        nonlocal ordem
        ordem += 1
        conn.execute(
            sa.text(
                "INSERT INTO pergunta (formulario_id, texto, ordem, tipo_resposta, escopo_id) "
                "VALUES (:fid, :texto, :ordem, 'nota', :escopo_id)"
            ),
            {"fid": formulario_id, "texto": texto, "ordem": ordem, "escopo_id": escopo_id},
        )

    for nome_escopo, perguntas in BLOCOS_TECNICOS.items():
        escopo_id = conn.execute(
            sa.text("SELECT id FROM escopo WHERE nome = :nome"), {"nome": nome_escopo}
        ).scalar()
        if not escopo_id:
            continue
        for texto in perguntas:
            inserir_pergunta(texto, escopo_id)

    for texto in BLOCO_FINAL_UNIVERSAL:
        inserir_pergunta(texto, None)


def downgrade() -> None:
    """Downgrade schema."""
    # Só desfaz o schema — reverter o catálogo de escopo (juntar de volta as
    # linhas renomeadas/adicionadas) e apagar as perguntas semeadas não é
    # seguro numa migration de dados: pode existir avaliação já respondida
    # apontando pra elas.
    # `None` (o que o autogenerate produz) falha no MySQL: drop_constraint
    # precisa do nome de verdade, e o autogerado aqui foi 'pergunta_ibfk_2'.
    op.drop_constraint('pergunta_ibfk_2', 'pergunta', type_='foreignkey')
    op.drop_index(op.f('ix_pergunta_escopo_id'), table_name='pergunta')
    op.drop_column('pergunta', 'escopo_id')
