from src.models.cargo_model import CargoModel
from src.models.escopo_model import EscopoModel
from src.models.usuario_model import UsuarioModel
from src.models.banca_model import BancaModel
from src.models.candidatura_model import CandidaturaModel
from src.models.semestre_model import SemestreModel
from src.models.formulario_model import FormularioModel
from src.models.pergunta_model import PerguntaModel
from src.models.avaliacao_model import AvaliacaoModel
from src.models.avaliacao_nota_model import AvaliacaoNotaModel
from src.models.frente_model import FrenteModel
from src.models.equipe_projeto_model import EquipeProjetoModel
from src.models.usuario_frente_model import UsuarioFrenteModel
from src.models.banca_frente_model import BancaFrenteModel
from src.models.configuracao_model import ConfiguracaoModel